# -*- coding: utf-8 -*-

# Copyright 2025 Prasanna Pakkiam
# SPDX-License-Identifier: Apache-2.0
# Author: Prasanna Pakkiam
# Creation Date: 02/06/2023
# Description: Collection of classes to draw different flux lines.

from qiskit_metal import draw
from qiskit_metal.toolbox_python.attr_dict import Dict
from qiskit_metal.qlibrary.core import QComponent
import numpy as np
import shapely

class FluxLineTPin(QComponent):
    """Create a flux line inlet in the form of a T which splits the current equally across 2 branches. Intended for an Xmon, but
    it can be used with any JJ SQUID loop.

    Inherits QComponent class.

    The Dolan Bridge consists of a T-Section followed by a Fork Section.

    Dolan Bridge Josephson Junction Metal Geometry (no Ground Cutout):
        * width - Width of the flux line T junction
        * pin_dist - Distance from the target pin (e.g. a section of an Xmon)
        * trace_width - CPW width of the flux line inlet (it is used for the T section)
        * trace_gap   - CPW gap of the flux line inlet (it is used for the T section)
        * orientation - orientation of the flux line T junction. 0 means the T is pointing to the right, 90 means the T is pointing up, etc.

    As usual, the positioning can be done dynamically as a vector given by the supplied parameters: (pos_x,pos_y) to (end_x,end_y)
        
    Pins:
        There are two pins:
            'a' - joins onto the flux-line inlet.
            't' - a point that is in line with the target pin - useful in aligning/placing SQUID loops or junctions

    Sketch:
        Below is a sketch of the Josephson Junction Shadow Evaporation masking template (there is no ground cut-out)
        ::

            @@@@@@@@@@@@@#####@      x = Target pin location
            @@@@@@@@@@@@@#####@      @ = Ground plane
            @@@@@@@@@@@@@##x##@      # = Reference target pin (in this case, it's aligned with pin_align_right=True)
            @@@@@@@@@@@@@     @D     W = width
            @@@@@@@@@@@@@  C  @D     S = trace_width
            @ _____________t_ @D     G = trace_gap
            @|______   ______|@      D = pin_dist
            @    G  |S|       @      a = Location of pin to which the flux line CPW attaches
            @@@@@@@@@a@@@@@@@@@      t = Location of pin that faces the target pin on the flux T junction
             W...............W       C = Ground cut-out generated by this structure to meet up with the reference target pin. Also,
                                         the usual location of the SQUID loop...
                   
    .. image::
        Cap3Interdigital.png

    .. meta::
        T-shaped Flux Line

    Default Options:
        * width='50um'
        * pin_dist='30um'
        * trace_width='20um'
        * trace_gap='20um'
    """

    default_options = Dict(ref_comp='', ref_pin='',
                           width='50um',
                           pin_dist='30um',
                           trace_width='20um',
                           trace_gap='20um',
                           pin_align_right=True,
                           orientation=0,
                           offset_y_pin = '0um')

    def make(self):
        """This is executed by the user to generate the qgeometry for the
        component."""
        p = self.p
        #########################################################

        jointPin = self._design.components[self.options.ref_comp].pins[self.options.ref_pin]
        ptJoint = jointPin['middle']
        normal = -jointPin['normal']
        rot_angle = np.arctan2(normal[1], normal[0]) - np.radians(p.orientation)
        targ_trace_width = jointPin['width']

        #The T-Section and Stem
        pad_T = [
                (0, p.width*0.5),
                (-p.trace_width, p.width*0.5),
                (-p.trace_width, p.trace_width*0.5),
                (-p.trace_width-p.trace_gap, p.trace_width*0.5),
                (-p.trace_width-p.trace_gap, -p.trace_width*0.5),
                (-p.trace_width, -p.trace_width*0.5),
                (-p.trace_width, -p.width*0.5),
                (0, -p.width*0.5)]
        pad_T = np.array(pad_T)
        
        pad_gap = [
                  (p.trace_gap, p.width*0.5),
                  (-p.trace_width-p.trace_gap, p.width*0.5),
                  (-p.trace_width-p.trace_gap, -p.width*0.5),
                  (p.pin_dist, -p.width*0.5),
                  (p.pin_dist, -p.width*0.5+targ_trace_width),
                  (p.trace_gap, -p.width*0.5+targ_trace_width)]
        pad_gap = np.array(pad_gap)

        if p.pin_align_right:
            pad_T[:,1] += (p.width-targ_trace_width)*0.5
            pad_gap[:,1] += (p.width-targ_trace_width)*0.5
        else:
            pad_T[:,1] += (-p.width+targ_trace_width)*0.5
            pad_gap[:,1] *= -1
            pad_gap[:,1] += (-p.width+targ_trace_width)*0.5
        pad_T[:,0] -= p.pin_dist
        pad_gap[:,0] -= p.pin_dist

        pin = pad_T[3:5]
        if p.pin_align_right:
            pin2 = [pad_T[-1], pad_T[-1]+np.array([0,targ_trace_width])]
        else:
            pin2 = [pad_T[0]-np.array([0,targ_trace_width]), pad_T[0]]

        pad_T = shapely.Polygon(pad_T)
        pad_gap = shapely.Polygon(pad_gap)
        pin = shapely.LineString(pin)
        pin2 = shapely.LineString(pin2)

        polys = [pad_T, pad_gap, pin, pin2]
        polys = draw.rotate(polys, rot_angle, origin=(0, 0), use_radians=True)
        polys = draw.translate(polys, *ptJoint)
        polys = draw.translate(polys, xoff=0, yoff=p.offset_y_pin)
        [pad_T, pad_gap, pin, pin2] = polys


        # Adds the object to the qgeometry table
        self.add_qgeometry('poly',
                           dict(flTjunc=pad_T),
                           layer=p.layer)

        #subtracts out ground plane on the layer it's on
        self.add_qgeometry('poly',
                           dict(padGap=pad_gap),
                           subtract=True,
                           layer=p.layer)

        # Generates its own pins
        self.add_pin('a', pin.coords[::-1], width=p.trace_width)
        self.add_pin('t', pin2.coords[::-1], width=targ_trace_width)


class FluxLineLPin(QComponent):
    """Create a flux line inlet in the form of a L which splits the current across 1 branch. Intended for an Xmon, but
    it can be used with any JJ SQUID loop.

    Inherits QComponent class.

    The Dolan Bridge consists of a T-Section followed by a Fork Section.

    Dolan Bridge Josephson Junction Metal Geometry (no Ground Cutout):
        * width - Width of the flux line T junction
        * pin_dist - Distance from the target pin (e.g. a section of an Xmon)
        * trace_width - CPW width of the flux line inlet (it is used for the T section)
        * trace_gap   - CPW gap of the flux line inlet (it is used for the T section)
        * orientation - orientation of the flux line T junction. 0 means the T is pointing to the right, 90 means the T is pointing up, etc.

    As usual, the positioning can be done dynamically as a vector given by the supplied parameters: (pos_x,pos_y) to (end_x,end_y)
        
    Pins:
        There are two pins:
            'a' - joins onto the flux-line inlet.
            't' - a point that is in line with the target pin - useful in aligning/placing SQUID loops or junctions

    Sketch:
        Below is a sketch of the Josephson Junction Shadow Evaporation masking template (there is no ground cut-out)
        ::

            @@@@@@@@@@@@@#####@      x = Target pin location
            @@@@@@@@@@@@@#####@      @ = Ground plane
            @@@@@@@@@@@@@##x##@      # = Reference target pin (in this case, it's aligned with pin_align_right=True)
            @@@@@@@@@@@@@     @D     W = width
            @@@@@@@@@@@@@  C  @D     S = trace_width
            @@@@@@  _______t_ @D     G = trace_gap
            @@@@@@ |  ______|@      D = pin_dist
            @@@@@@ |S|   G   @      a = Location of pin to which the flux line CPW attaches
            @@@@@@@@@a@@@@@@@@@      t = Location of pin that faces the target pin on the flux L junction
                    W........W       C = Ground cut-out generated by this structure to meet up with the reference target pin. Also,
                                         the usual location of the SQUID loop...
                   
    .. image::
        Cap3Interdigital.png

    .. meta::
        L-shaped Flux Line

    Default Options:
        * width='50um'
        * pin_dist='30um'
        * trace_width='20um'
        * trace_gap='20um'
    """

    default_options = Dict(ref_comp='', ref_pin='',
                           width='50um',
                           pin_dist='30um',
                           trace_width='20um',
                           trace_gap='20um',
                           pin_align_right=True,
                           orientation=0,
                           offset_y_pin = '0um')

    def make(self):
        """This is executed by the user to generate the qgeometry for the
        component."""
        p = self.p
        #########################################################

        jointPin = self._design.components[self.options.ref_comp].pins[self.options.ref_pin]
        ptJoint = jointPin['middle']
        normal = -jointPin['normal']
        rot_angle = np.arctan2(normal[1], normal[0]) - np.radians(p.orientation)
        targ_trace_width = jointPin['width']

        #The L-Section and Stem
        pad_L = [
                (0, p.trace_width*0.5),
                (-p.trace_width,p.trace_width*0.5),
                (-p.trace_width, p.trace_width*0.5),
                (-p.trace_width-p.trace_gap, p.trace_width*0.5),
                (-p.trace_width-p.trace_gap, -p.trace_width*0.5),
                (-p.trace_width, -p.trace_width*0.5),
                (-p.trace_width, -p.width),
                (0, -p.width)]
        pad_L = np.array(pad_L)
        
        pad_gap = [
                  (p.trace_gap, p.trace_gap),#p.width*0.5),
                  (-p.trace_width-p.trace_gap, p.trace_gap),# p.width*0.5),
                  (-p.trace_width-p.trace_gap, -p.width),
                  (p.trace_gap, -p.width),
                  (p.trace_gap, -p.width+targ_trace_width),
                  (p.trace_gap, -p.width+targ_trace_width)]
        pad_gap = np.array(pad_gap)

        if p.pin_align_right:
            pad_L[:,1] += (p.width-targ_trace_width/2)
            pad_gap[:,1] += (p.width-targ_trace_width/2)
        else:
            pad_L[:,1] += (-p.width+targ_trace_width/2)
            pad_gap[:,1] *= -1
            pad_gap[:,1] += (-p.width+targ_trace_width/2)
        pad_L[:,0] -= p.pin_dist
        pad_gap[:,0] -= p.pin_dist

        pin = pad_L[3:5]
        if p.pin_align_right:
            pin2 = [pad_L[-1], pad_L[-1]+np.array([0,targ_trace_width])]
        else:
            pin2 = [pad_L[0]-np.array([0,targ_trace_width]), pad_L[0]]

        pad_L = shapely.Polygon(pad_L)
        pad_gap = shapely.Polygon(pad_gap)
        pin = shapely.LineString(pin)
        pin2 = shapely.LineString(pin2)

        polys = [pad_L, pad_gap, pin, pin2]
        polys = draw.rotate(polys, rot_angle, origin=(0, 0), use_radians=True)
        polys = draw.translate(polys, *ptJoint)
        polys = draw.translate(polys, xoff=0, yoff=p.offset_y_pin)
        [pad_L, pad_gap, pin, pin2] = polys


        # Adds the object to the qgeometry table
        self.add_qgeometry('poly',
                           dict(flTjunc=pad_L),
                           layer=p.layer)

        #subtracts out ground plane on the layer it's on
        self.add_qgeometry('poly',
                           dict(padGap=pad_gap),
                           subtract=True,
                           layer=p.layer)

        # Generates its own pins
        self.add_pin('a', pin.coords[::-1], width=p.trace_width)
        self.add_pin('t', pin2.coords[::-1], width=targ_trace_width)


# -*- coding: utf-8 -*-
"""
Copyright 2026 [Your Name]
SPDX-License-Identifier: Apache-2.0
Author: [Your Name]
Creation Date: 2026-04-10
Description: FluxLineCircle class for SQDMetal - circular flux line for strong SQUID coupling.
"""

from qiskit_metal import draw
from qiskit_metal.toolbox_python.attr_dict import Dict
from qiskit_metal.qlibrary.core import QComponent
import numpy as np
import shapely
from shapely.geometry import LineString, Polygon

class FluxLineCircle(QComponent):
    """
    Circular flux line component for strong inductive coupling to SQUID loops.
    
    Creates a CPW flux line with a circular arc section positioned near the SQUID
    for strong mutual inductance, and a straight tail routed outward so the pin
    ends outside the transmon pocket.
    
    Matches the style of FluxLineLPin/TPin with polygon metal + gap subtract.
    
    Positioning:
    * References a qubit pin (typically 'pinisland') 
    * Circle is offset from that pin by circle_offset_x/y
    * Tail exits in tail_direction and extends to outside the pocket
    
    Pins:
    * 'a': outer pin on the tail end (for connecting to wiring)
    * 't': reference pin aligned toward the qubit pin (like LPin/TPin)
    
    Sketch:
    ```
    @@@@@@@@@@@#####@ x = target qubit pin
    @@@@@@@@@@@#####@ @ = ground plane
       _____     # = qubit pinisland pin
     /     \   ## = circle arc (high current density near SQUID)
    |  O O  |  x  O = SQUID loop location
     \_  __/
      |  |
      |  | tail (straight CPW)
    __|  |
         a
    ```
    
    Default Options:
    * trace_width='8um'
    * trace_gap='12um'
    * circle_radius='20um'
    * arc_start_angle='40deg' (start angle in degrees)
    * arc_end_angle='300deg' (end angle in degrees) 
    * circle_offset_x='0um'
    * circle_offset_y='0um'
    * tail_direction='right'
    * tail_length='150um'
    * pin_dist='30um'
    * pin_align_right=True
    * layer='1'
    """
    
    default_options = Dict(
        ref_comp='',           # qubit component name
        ref_pin='pinisland',   # qubit pin name (typically pinisland for SQUID)
        
        # CPW parameters
        trace_width='8um',
        trace_gap='12um',
        layer='1',
        
        # Circle parameters
        circle_radius='20um',
        arc_start_angle=40,   # degrees, CCW from +x axis
        arc_end_angle=300,    # degrees, CCW from +x axis
        circle_offset_x='0um',
        circle_offset_y='0um',
        
        # Tail parameters
        tail_direction='right',    # 'left', 'right', 'up', 'down'
        tail_length='150um',
        tail2_length = '100um', 
        tail3_length = '50um',  # extra tail perpendicular to main tail with open end
        
        # Pin alignment (like LPin/TPin)
        pin_dist='30um',
        pin_align_right=True,
        orientation=0,
        
        # Offsets
        offset_x='0um',
        offset_y='0um'
    )
    
    def make(self):
        """
        The make method that generates the qgeometry for the component.
        """
        p = self.p
        
        # Get reference pin from qubit
        qubit_comp = self._design.components[p.ref_comp]
        ref_pin_name = p.ref_pin
        ref_pin = qubit_comp.pins[ref_pin_name]
        pt_ref = ref_pin['middle']
        normal = -ref_pin['normal']  # outward normal
        targ_trace_width = ref_pin['width']
        
        # Component rotation angle
        rot_angle = np.radians(p.orientation)
        
        # Circle center relative to reference pin
        circle_center = np.array([p.circle_offset_x, p.circle_offset_y])
        
        # Generate circle arc centerline points
        theta_start = np.radians(p.arc_start_angle)
        theta_end = np.radians(p.arc_end_angle)
        n_points = 32  # enough for smooth arc
        thetas = np.linspace(theta_start, theta_end, n_points)
        arc_points = circle_center[:, np.newaxis] + p.circle_radius * np.array([np.cos(thetas), np.sin(thetas)])
        
        # Tail direction vector (unit vector)
        dir_map = {'right': np.array([1, 0]),
                   'left': np.array([-1, 0]),
                   'up': np.array([0, 1]),
                   'down': np.array([0, -1])}
        tail_dir = dir_map[p.tail_direction.lower()]
        
        # Bridge: short connection from arc end to tail start (tangential-ish)
        arc_start_pt = arc_points[:, 0]
        arc_end_pt = arc_points[:, -1]
        bridge_start = arc_end_pt + 0.5 * p.circle_radius * np.array([-np.sin(theta_end), np.cos(theta_end)])  # tangential
        bridge_end = bridge_start + 1.0 * p.trace_width * tail_dir
        bridge_points = np.vstack([bridge_start, bridge_end])
        bridge2_start = arc_start_pt #+ 0.5 * p.circle_radius * np.array([-np.sin(theta_start), np.cos(theta_start)])  # tangential
        bridge2_end = bridge2_start + 1.0 * p.trace_width * tail_dir
        bridge2_points = np.vstack([bridge2_start, bridge2_end])    
        
        # Tail: straight outward to pin location
        tail_end = bridge_end + p.tail_length * tail_dir
        tail_points = np.vstack([bridge_end, tail_end])
        tail2_end = bridge2_end + p.tail2_length * tail_dir
        tail2_points = np.vstack([bridge2_end, tail2_end])
        tail3_end = tail2_end + p.tail3_length * np.array([-tail_dir[1], tail_dir[0]])  # perpendicular to tail
        tail3_points = np.vstack([tail3_end, tail2_end])
        
        # Full centerline path: arc + bridge + tail
        centerline = np.vstack([tail3_points,tail2_points, bridge2_points, arc_points.T, bridge_points, tail_points])
        centerline_path = LineString(centerline)
        
        # Reference pin 't' (aligned toward qubit pin, like LPin)
        if p.pin_align_right:
            pin_t_start = arc_points[:, 0]  # arc start
            pin_t_end = pin_t_start + np.array([0, targ_trace_width])
        else:
            pin_t_start = arc_points[:, 0] - np.array([0, targ_trace_width])
            pin_t_end = arc_points[:, 0]
        pin_t = LineString([pin_t_start, pin_t_end])
        
        # Main pin 'a' at tail end
        pin_a_start = tail_end - 0.5 * p.trace_width * np.array([0, 1])
        pin_a_end = tail_end + 0.5 * p.trace_width * np.array([0, 1])
        pin_a = LineString([pin_a_start, pin_a_end])
        
        # Metal polygons: centerline buffered
        metal = centerline_path.buffer(p.trace_width / 2, cap_style=1, join_style=1)
        
        # Gap subtract: inflated centerline
        #gap_width = p.trace_width + 2 * p.trace_gap
        #subtract_path = centerline_path.buffer(gap_width / 2, cap_style=1, join_style=1)
        gap_width = p.trace_width + 2 * p.trace_gap

        main_gap_path = LineString(np.vstack([tail2_points, bridge2_points, arc_points.T, bridge_points, tail_points])).buffer(gap_width / 2, cap_style=1, join_style=1)

        tail3_gap_path = LineString(tail3_points).buffer(gap_width / 2,cap_style=2,join_style=1)

        subtract_path = main_gap_path.union(tail3_gap_path)
        
        # Transform everything: rotate, translate to ref pin + offsets
        all_shapes = [metal, subtract_path, pin_a, pin_t, centerline_path]
        all_shapes = draw.rotate(all_shapes, rot_angle, origin=(0.0, 0.0))
        all_shapes = draw.translate(all_shapes, pt_ref[0] + p.pin_dist, pt_ref[1] + p.offset_y)
        
        metal, subtract_path, pin_a, pin_t, _ = all_shapes
        
        # Add to qgeometry
        self.add_qgeometry('poly', {'flux_circle': metal}, layer=p.layer)
        self.add_qgeometry('poly', {'gap': subtract_path}, layer=p.layer, subtract=True)
        
        # Add pins
        self.add_pin('a', pin_a.coords[::-1], width=p.trace_width)
        self.add_pin('t', pin_t.coords[::-1], width=targ_trace_width)

class FluxLineLCutout(QComponent):
    '''
    This Class is similar to the the FluxLineLPin but instead of moving the squid close to the outside of the pocket, we create a cutout in the ground plane that allows the flux line to get closer to the squid loop. 
    This is useful for designs with tight space constraints where we want to maximize the mutual inductance between the flux line and the SQUID loop. 

    This class will simply call the existing FluxLineLPin to create the flux line geometry, and then add an additional polygon to the qgeometry that will be subtracted from the ground plane. 
    The cutout will be a rectangle that extends from the end of the flux line to the reference pin

    

    '''