name: Windows

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]

    env:
      PYTHONIOENCODING: "utf8"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Mamba & Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          miniconda-version: "latest"
          activate-environment: sqdmetal_env
          python-version: "3.11"
          use-mamba: true
          auto-update-conda: true
          environment-file: # Uncomment if you use this file

      - name: Cache Conda packages
        uses: actions/cache@v4
        with:
          path: |
            ~/miniconda/pkgs
            C:\Miniconda3\pkgs
          key: conda-\({{ runner.os }}-\){{ hashFiles('env_windows.yml') }}
          restore-keys: |
            conda-${{ runner.os }}-

      - name: Install the package in editable mode
        shell: bash -el {0}  # <--- -el {0} ensures the conda environment is active
        run: |
          python -m pip install -e .

      - name: Run unittest tests
        shell: bash -el {0}  # <--- -el {0} ensures the conda environment is active
        run: |
          python -m unittest discover -s UnitTests
