name: Windows

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    name: Windows
    runs-on: windows-latest

    # XXX Workaround for Windows runners redirecting the output of commands to files.
    # See: https://github.com/databrickslabs/dbx/issues/455#issuecomment-1312770919
    env:
      PYTHONIOENCODING: utf-8

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: latest
          auto-activate-base: false

      - name: Cache Conda packages
        uses: actions/cache@v4
        with:
          path: |
            C:\Miniconda3\pkgs
          key: conda-windows-${{ hashFiles('env_windows.yml') }}
          restore-keys: |
            conda-windows-

      - name: Create fresh Conda environment
        shell: bash -el {0}
        run: |
          conda env create -n sqdmetal_env python==3.11
          conda activate sqdmetal_env
          python --version
          conda info --envs

      - name: Install package
        shell: bash -el {0}
        run: |
          conda activate sqdmetal_env
          python -m pip install -e .

      - name: Run unittest tests
        shell: bash -el {0}
        run: |
          conda activate sqdmetal_env
          python -m unittest discover -s UnitTests
