name: Windows

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]

    env:
      PYTHONIOENCODING: "utf8"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Mamba & Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          miniconda-version: "latest"
          activate-environment: sqdmetal_env
          python-version: "3.11"
          use-mamba: true
          auto-update-conda: true
          environment-file: # If you have a yml file, point to it here, e.g., env_windows.yml

      # Optional: Add caching if you have heavy dependencies in a YML file
      - name: Cache Conda environment
        uses: actions/cache@v4
        with:
          path: ~/miniconda/envs/sqdmetal_env
          key: conda-\({{ runner.os }}-\){{ hashFiles('env_windows.yml') }}-${{ env.date }}
        if: hashFiles('env_windows.yml') != ''

      - name: Install the package in editable mode
        shell: bash
        run: |
          C:/Miniconda3/envs/sqdmetal_env/python.exe -m pip install -e .

      - name: Run unittest tests
        shell: bash
        run: |
          C:/Miniconda3/envs/sqdmetal_env/python.exe -m unittest discover -s UnitTests
